@startuml payment-info
actor Customer
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
database "Database" as db
Customer -> system: Entering payment info
activate system
system -> db: savePayment(username, payment)
activate db
db --> system: none
deactivate db
system -> system: Display that it is done
Customer -> system: Press done
system -> system: Displays thank you. Goes to home page
deactivate system
@enduml